import '../codec/veil_codec.dart';

// Byte tables consumed by the veil codec. Regenerated by the mint
// tool; every entry is an encoded form of a single string that
// `reveal()` turns back into plaintext at runtime.

const List<int> _endpointUrl = <int>[
  163, 60, 162, 199, 252, 75, 51, 147, 133, 70, 29, 111,
  153, 153, 107, 101, 18, 219, 189, 94, 154, 170, 149, 174,
  217, 14, 3, 120, 233, 162, 212, 29, 45, 71, 96,
];

const List<int> _gcdBaseUrl = <int>[
  163, 60, 162, 199, 252, 75, 51, 147, 139, 70, 28, 126,
  146, 135, 43, 96, 15, 210, 186, 80, 216, 191, 153, 178,
  156, 66, 9, 113, 161, 174, 149, 29, 32, 72, 111, 25,
  179, 175, 41, 162, 214, 160, 7, 40, 146, 220, 10,
];

const List<int> _attributionKey = <int>[
  253, 3, 134, 221, 224, 48, 122, 239, 153, 124, 22, 100,
  207, 190, 67, 56, 11, 203, 135, 108, 247, 158,
];

const List<int> _messagingProject = <int>[
  255, 120, 224, 143, 190, 67, 36, 132, 221, 16, 65, 57,
];

const List<int> _relaySecret = <int>[
  141, 56, 133, 230, 198, 9, 36, 255, 173, 110, 76, 105,
  146, 190, 95, 114, 77, 225, 190, 4, 211, 139, 205, 241,
  202, 77, 14, 70, 221, 182, 141, 91, 36, 111, 97, 64,
  137, 250, 28, 186, 227, 224, 73,
];

const List<int> _uaProduct = <int>[
  134, 39, 172, 222, 227, 29, 125, 147, 217, 11, 72,
];

const List<int> _uaLinuxOpen = <int>[
  227, 4, 191, 217, 250, 9, 39, 156, 173, 75, 28, 127,
  153, 133, 97,
];

const List<int> _uaBuildLabel = <int>[
  235, 10, 163, 222, 227, 21, 51,
];

const List<int> _uaBuildClose = <int>[
  226,
];

const List<int> _uaEngineLabel = <int>[
  235, 9, 166, 199, 227, 20, 75, 217, 142, 110, 17, 121,
  217,
];

const List<int> _uaEngineTail = <int>[
  235, 96, 157, 255, 219, 60, 80, 144, 204, 73, 17, 102,
  147, 204, 66, 100, 28, 201, 166, 31,
];

const List<int> _uaChromeLabel = <int>[
  235, 11, 190, 197, 224, 28, 121, 147,
];

const List<int> _uaMobileSafari = <int>[
  235, 5, 185, 213, 230, 29, 121, 156, 191, 68, 30, 108,
  132, 133, 42,
];

const List<int> _chromeVersion = <int>[
  250, 124, 239, 153, 191, 95, 43, 139, 216, 23, 86, 60,
  199, 222,
];

const List<int> _webkitVersion = <int>[
  254, 123, 225, 153, 188, 71,
];

const List<int> _jsSafeAreaScript = <int>[];

const List<int> _jsKeyboardScript = <int>[];

const List<int> _jsKeyboardBridge = <int>[];

const List<int> _jsAutoplayScript = <int>[];

String unlockEndpointUrl() => reveal(_endpointUrl);
String unlockGcdBaseUrl() => reveal(_gcdBaseUrl);
String unlockAttributionKey() => reveal(_attributionKey);
String unlockMessagingProject() => reveal(_messagingProject);
String unlockRelaySecret() => reveal(_relaySecret);

String unlockUaProduct() => reveal(_uaProduct);
String unlockUaLinuxOpen() => reveal(_uaLinuxOpen);
String unlockUaBuildLabel() => reveal(_uaBuildLabel);
String unlockUaBuildClose() => reveal(_uaBuildClose);
String unlockUaEngineLabel() => reveal(_uaEngineLabel);
String unlockUaEngineTail() => reveal(_uaEngineTail);
String unlockUaChromeLabel() => reveal(_uaChromeLabel);
String unlockUaMobileSafari() => reveal(_uaMobileSafari);
String unlockChromeVersion() => reveal(_chromeVersion);
String unlockWebkitVersion() => reveal(_webkitVersion);

String unlockJsSafeAreaScript() => reveal(_jsSafeAreaScript);
String unlockJsKeyboardScript() => reveal(_jsKeyboardScript);
String unlockJsKeyboardBridge() => reveal(_jsKeyboardBridge);
String unlockJsAutoplayScript() => reveal(_jsAutoplayScript);

String unlockGcdCallUrl(String applicationId, String deviceId) {
  final String base = unlockGcdBaseUrl();
  if (base.isEmpty) return '';
  return '$base$applicationId?devkey=${unlockAttributionKey()}&device_id=$deviceId';
}
